Ext.define('withub.ext.std.workCalendar.WorkCalendar', {
    extend:'withub.ext.common.Window',
    title:'工作日历',
    baseUrl:'/std/workCalendar',
    initComponent:function () {
        this.formPanel = Ext.create('Ext.form.Panel', {
            bodyStyle:'padding: 5px 10px',
            border:false,
            baseCls:'x-plain',
            defaultType:'textfield',
            defaults:{
                labelWidth:95,
                anchor:'100%'
            },
            items:[
                {
                    fieldLabel:'名称',
                    name:'name',
                    maxLength:100,
                    allowBlank:false
                },
                {
                    xtype:'radiogroup',
                    fieldLabel:'默认日历',
                    allowBlank:false,
                    columns:4,
                    items:[
                        {boxLabel:'是', name:'defaultCalendar', inputValue:1, checked:true},
                        {boxLabel:'否', name:'defaultCalendar', inputValue:0}
                    ]
                },
                {
                    xtype:'radiogroup',
                    fieldLabel:'周末节假日',
                    allowBlank:false,
                    columns:4,
                    items:[
                        {boxLabel:'是', name:'weekendHoliday', inputValue:1, checked:true},
                        {boxLabel:'否', name:'weekendHoliday', inputValue:0}
                    ]
                },
                {
                    xtype:'numberfield',
                    fieldLabel:'天工作小时',
                    name:'dayHours',
                    allowDecimals:false,
                    minValue:6,
                    maxValue:12,
                    value:8,
                    allowBlank:false
                },
                {
                    xtype:'fieldcontainer',
                    layout:'hbox',
                    items:[
                        {
                            xtype:'timefield',
                            fieldLabel:'上午时间',
                            name:'forenoonStartTime',
                            increment:30,
                            labelWidth:95,
                            format:'H:i',
                            flex:4,
                            minValue:'08:00',
                            anchor:'100%',
                            value:'09:00',
                            allowBlank:false
                        },
                        {
                            xtype:'splitter',
                            flex:1
                        },
                        {
                            xtype:'timefield',
                            fieldLabel:'到',
                            name:'forenoonEndTime',
                            increment:30,
                            labelWidth:55,
                            maxWidth:180,
                            format:'H:i',
                            flex:4,
                            minValue:'08:00',
                            value:'12:00',
                            anchor:'100%',
                            allowBlank:false
                        }
                    ]
                },
                {
                    xtype:'fieldcontainer',
                    layout:'hbox',
                    items:[
                        {
                            xtype:'timefield',
                            fieldLabel:'下午时间',
                            name:'afternoonStartTime',
                            increment:30,
                            labelWidth:95,
                            format:'H:i',
                            flex:4,
                            minValue:'08:00',
                            anchor:'100%',
                            value:'12:30',
                            allowBlank:false
                        },
                        {
                            xtype:'splitter',
                            flex:1
                        },
                        {
                            xtype:'timefield',
                            fieldLabel:'到',
                            name:'afternoonEndTime',
                            increment:30,
                            maxWidth:180,
                            labelWidth:55,
                            format:'H:i',
                            flex:4,
                            minValue:'08:00',
                            value:'17:30',
                            anchor:'100%',
                            allowBlank:false
                        }
                    ]
                },
                {
                    fieldLabel:'描述',
                    xtype:'textarea',
                    height:150,
                    name:'description'
                },
                {
                    xtype:'hidden',
                    name:'objectId'
                }
            ]
        });

        this.items = [this.formPanel];

        this.callParent();
    }
});

